import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myFont = localFont({
  src: '../../fonts/mayaboti-normal.ttf'
})

export const metadata = {
  title: "Kidz Bazar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-base-100">
        <header>
          <Navbar></Navbar>
        </header>
      
        <main className={myFont.className}>
          {children}
        </main>

        <footer>

        </footer>
      </body>
    </html>
  );
}
